import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as prettier from 'prettier';
import { renderTimeMd } from '../src/render.js';
import type { LedgerEvent } from '../src/ledger.js';

const base = { v: 1 as const, session: 'aaaaaaaa-1111', harness: 'claude-code' as const };

const events: LedgerEvent[] = [
  { ...base, ts: '2026-10-05T09:00:00.000-04:00', event: 'step-start', step: 'brief', estimateMin: 30 },
  { ...base, ts: '2026-10-05T09:20:00.000-04:00', event: 'stop', step: 'brief' },
  { ...base, ts: '2026-10-05T09:20:00.000-04:00', event: 'step-finish', step: 'brief' },
  { ...base, ts: '2026-10-05T10:00:00.000-04:00', event: 'step-start', step: 'S1', session: null, harness: 'shell' },
];

test('time.md lists every step with totals and a generated-file notice', () => {
  const expected = `---
doc: time
updated: 2026-10-05
---

# Time: 2026-10-05-sample

Generated by \`worklog render\` from \`time.jsonl\`. Do not edit by hand.

| Step      | Estimate | Started          | Finished         | Wall | Active | Sessions               |
| --------- | -------- | ---------------- | ---------------- | ---- | ------ | ---------------------- |
| brief     | 30m      | 2026-10-05 09:00 | 2026-10-05 09:20 | 20m  | 20m    | aaaaaaaa (claude-code) |
| S1        |          | 2026-10-05 10:00 | open             | —    | —      |                        |
| **Total** | 30m      |                  |                  | 20m  | 20m    |                        |

Active time counts agent turns plus up to 5 minutes of each wait for a person, and no single gap
counts more than 30 minutes. \`—\` means nothing was recorded.
`;
  assert.equal(renderTimeMd('2026-10-05-sample', events), expected);
});

test('time.md is already formatted the way Prettier would format it', async () => {
  const output = renderTimeMd('2026-10-05-sample', events);
  const formatted = await prettier.format(output, { parser: 'markdown', printWidth: 100 });
  assert.equal(formatted, output);
});
