import { computeTimes, IDLE_CAP_MS, TURN_CAP_MS } from './active.js';
import { formatMinutes } from './duration.js';
import type { LedgerEvent } from './ledger.js';

const NONE = '—';
const HEADER = ['Step', 'Estimate', 'Started', 'Finished', 'Wall', 'Active', 'Sessions'];

function shown(ts: string): string {
  return `${ts.slice(0, 10)} ${ts.slice(11, 16)}`;
}

function duration(ms: number | null): string {
  return ms === null ? NONE : formatMinutes(ms / 60_000);
}

/** Lays out a table exactly as Prettier does, so a formatter pass leaves it unchanged. */
function table(rows: string[][]): string {
  const widths = HEADER.map((_, col) => Math.max(3, ...rows.map((row) => (row[col] ?? '').length)));
  const line = (cells: string[]): string => `| ${cells.map((c, i) => c.padEnd(widths[i] ?? 0)).join(' | ')} |`;
  const [header, ...body] = rows;
  return [line(header ?? []), line(widths.map((w) => '-'.repeat(w))), ...body.map(line)].join('\n');
}

/** Renders `time.md` for a feature folder from its ledger events. */
export function renderTimeMd(folder: string, events: LedgerEvent[]): string {
  const times = computeTimes(events);
  const latest = events.reduce<LedgerEvent | undefined>(
    (best, e) => (best === undefined || Date.parse(e.ts) >= Date.parse(best.ts) ? e : best),
    undefined,
  );
  const rows = times.steps.map((s) => [
    s.step,
    s.estimateMin === null ? '' : formatMinutes(s.estimateMin),
    shown(s.started),
    s.finished === null ? 'open' : shown(s.finished),
    duration(s.wallMs),
    duration(s.activeMs),
    s.sessions.map((r) => `${r.session.slice(0, 8)} (${r.harness})`).join(', '),
  ]);
  const total = [
    '**Total**',
    times.total.estimateMin === null ? '' : formatMinutes(times.total.estimateMin),
    '',
    '',
    duration(times.total.wallMs),
    duration(times.total.activeMs),
    '',
  ];
  return `---
doc: time
updated: ${latest ? latest.ts.slice(0, 10) : ''}
---

# Time: ${folder}

Generated by \`worklog render\` from \`time.jsonl\`. Do not edit by hand.

${table([HEADER, ...rows, total])}

Active time counts agent turns plus up to ${IDLE_CAP_MS / 60_000} minutes of each wait for a person, and no single gap
counts more than ${TURN_CAP_MS / 60_000} minutes. \`${NONE}\` means nothing was recorded.
`;
}
